### ISSUE TITLE
feat: parse "files" in package.json and/or .npmignore for improper devDependencies usage

### ISSUE THREAD

**Issue by clshortfuse** [eslint-community/eslint-plugin-n#103]
When a file to be packaged imports from a dev dependency, an error should be thrown.

Here is a citation from the documentation for the `files` field in `package.json`:

>The optional files field is an array of file patterns that describes the entries to be included when your package is installed as a dependency. File patterns follow a similar syntax to .gitignore, but reversed: including a file, directory, or glob pattern (, **/, and such) will make it so that file is included in the tarball when it's packed. Omitting the field will make it default to ["*"], which means it will include all files.

https://docs.npmjs.com/cli/v9/configuring-npm/package-json#files

Some special files and directories are also included or excluded regardless of whether they exist in the files array (see below).

You can also provide a .npmignore file in the root of your package or in subdirectories, which will keep files from being included. At the root of your package it will not override the "files" field, but in subdirectories it will. The .npmignore file works just like a .gitignore. If there is a .gitignore file, and .npmignore is missing, .gitignore's contents will be used instead.

Files included with the "package.json#files" field cannot be excluded through .npmignore or .gitignore.

Therefore, it should be reasonable we can conclude the following:

* if the JSFILE has an import that is in devDependencies and the JSFILE is to be included
* then throw `${Dependency} should be listed in "dependencies" instead of "devDependencies"`

* if the JSFILE has an import that is not in dependencies and the JSFILE is to be included
* then throw `${Dependency} is missing in "dependencies"`

* if the JSFILE has an import that is not in devDependencies and the JSFILE is NOT to be included
* then throw `${Dependency} is missing in "devDependencies"`

If the `files` field is blank, then `.npmignore` is to be checked. If there is no `.npmignore` then, then check `.gitignore`.

**Comment by aladdin-add** [comment]
Are you proposing a new rule to do it? it already provides two similar rules:

* https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/no-unpublished-import.md
* https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/no-unpublished-require.md

**Comment by clshortfuse** [comment]
Sorry. it's my mistake. I had "files" as a `string`, not an `Array` and assumed the behavior wasn't in the eslint ruleset. Thanks!
