### ISSUE TITLE
Autodetect module type in recommends for `FlatConfig`

### ISSUE THREAD

**Issue by coderaiser** [eslint-community/eslint-plugin-n#105]
Would be great to have ability to require `recommended` preset with auto detect `ESM`/`CommonJS` in a similar to `CommonJS` way:

```js
const nodeRecommendedScript = require("eslint-plugin-n/configs/recommended-script");

module.exports = [
    nodeRecommendedScript,
    {
        rules: {
            "n/exports-style": ["error", "module.exports"]
        }
    }
]
```

So it looks like:

```js
const nodeRecommended = require("eslint-plugin-n/configs/recommended");

module.exports = [
    nodeRecommended,
]
```

**Comment by coderaiser** [comment]
Could you please publish new version :)?

**Comment by aladdin-add** [comment]
I'll release it when https://github.com/eslint-community/eslint-plugin-n/pull/114 get merged.

**Comment by coderaiser** [comment]
I have an error:

```
TypeError: Key "plugins": Cannot redefine plugin "n".
```

<img width="669" alt="image" src="https://github.com/eslint-community/eslint-plugin-n/assets/1573141/ac022118-34c3-4ac2-b411-7ae03c47b377">

<img width="634" alt="image" src="https://github.com/eslint-community/eslint-plugin-n/assets/1573141/d385a65b-bda0-427e-aa25-6bc37039a2dd">

**Comment by aladdin-add** [comment]
what is your config?

**Comment by aladdin-add** [comment]
seems like it's an issue that has been fixed. can you upgrade eslint to latest and retry?

https://github.com/eslint/eslint/issues/16277

**Comment by aladdin-add** [comment]
technically you cannot define a namespace for more than 2 plugins:

```js
[plugins: {n: obj1}],
[plugins: {n: obj2}],
```

it will throw an error as you described.

In your case, you were using eslintrc and flat configs:
`@eslint/eslintrc` to translate `plugins: ["n"]` to `plugins: {n: obj}`. which is a normalized plugin object.

**Comment by aladdin-add** [comment]
so, this is not an issue in the package. I would recommend converting all the used `eslint-plugin-n` configs to flat. 

I'm willing to make a PR for putout if you like. :)

**Comment by aladdin-add** [comment]
it should be resolved by removing this line:
https://github.com/coderaiser/putout/blob/4fac9bf44e80dd79d37ba7b93289b4fb531d8fc2/packages/eslint-plugin-putout/lib/index.js#L109

**Comment by coderaiser** [comment]
What about this rules I disabled?

<img width="460" alt="image" src="https://github.com/eslint-community/eslint-plugin-n/assets/1573141/b7a6c63c-c5e2-4c83-9617-34c86ef53692">

Plugin `n` not required for them? And if it is absent they will be just ignored, is it right?

It works good, thank you!
