### ISSUE TITLE
Typescript extension mapping

### ISSUE THREAD

**Issue by scagood** [eslint-community/eslint-plugin-n#108]
#### Prior issues:
- [Typescript extensions should include tsx #47](https://github.com/eslint-community/eslint-plugin-n/issues/47)
- [fix: missing import recognise tsx extension #97](https://github.com/eslint-community/eslint-plugin-n/pull/97)

#### Description:
In the tsconfig file you can change whether `.tsx` becomes `.jsx`, or `.js`. Currently ([as far as I can see](https://github.com/eslint-community/eslint-plugin-n/blob/master/lib/util/map-typescript-extension.js#L6-L19)) only `.tsx` <-> `.jsx` is supported (this is the `jsx: 'preserve'` option (https://www.typescriptlang.org/tsconfig#jsx)

I would like to add a mecanism to specify what exension `.tsx` becomes.

#### Proposals
There are a couple of methods that come to mind:
1. We could detect the tsconfig (using typescript, then automatically change the mapping.
```js
import { dirname } from 'node:path';
import { sys, findConfigFile, readConfigFile, parseJsonConfigFileContent } from 'typescript';

const tsconfigPath = findConfigFile(filePath, sys.fileExists, 'tsconfig.json');
if (tsconfigPath == null) {
  // No ts, no mapping
  return {};
}
const tsconfigFile = readConfigFile(tsconfigPath, sys.readFile);
const config = parseJsonConfigFileContent(tsconfigFile.config, sys, dirname(tsconfigPath));

// Now we can check `config.options.jsx`
```
2. We could detect the tsconfig (using [get-tsconfig](https://www.npmjs.com/package/get-tsconfig), then automatically change the mapping.
```js
import { getTsconfig } from 'get-tsconfig';

const cache = new Map();
const { config } = getTsconfig(filePath, 'tsconfig.json', cache);

// Now we can check `config.options.jsx`
```
3. We could provide a setting in the rules to configure the mappings, eg:
```js
settings: {
  node: {
    typescriptExtensionMapping: {
      '.ts': '.js',
      '.cts': '.cjs',
      '.mts': '.mjs',
      '.tsx': '.jsx'
    }
  }
}
```

#### Additional
I am happy to work with (make a PR) for any of these options, or another if there is a better one!

Personally I prefer the last option as its the lightest weight, and if something changes in the future we don't need to worry immediatly as its just a userland config option.

**Comment by aladdin-add** [comment]
Thanks for the input! To me solution 3 seems to be the easiest and most reliable. But 1 or 2 also SGTM if the feature can be opt-in and not affect non-js users.

question: will solution 1 work if the config was extending another file? e.g.

```json
{
"extend": "@my-shared-tsconfig", // having the config here
}
```

**Comment by aladdin-add** [comment]
the option `typescriptExtensionMapping` can be also configured with the rule options, like `node.versions`: https://github.com/eslint-community/eslint-plugin-n#configured-nodejs-version-range

**Comment by scagood** [comment]
After some testing its considerably faster to use `get-tsconfig`

<details>
<summary>Test code:</summary>

```ts
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';
import typescript from 'typescript';

import { getTsconfig } from 'get-tsconfig';
const cache = new Map();

const JsxEmit = {
  0: 'none',
  1: 'preserve',
  2: 'react',
  3: 'react-native',
  4: 'react-jsx',
  5: 'react-jsxdev',
};

function getTypescriptJSX(filePath: string) {
  try {
    // const typescript = require('typescript').default;
    const { sys, readConfigFile, parseJsonConfigFileContent } = typescript;

    const tsconfigPath = typescript.findConfigFile(
      filePath,
      sys.fileExists,
      'tsconfig.json',
    );

    if (tsconfigPath != null) {
      const tsconfigFile = readConfigFile(tsconfigPath, sys.readFile);
      const config = parseJsonConfigFileContent(tsconfigFile.config, sys, dirname(tsconfigPath));

      const jsx = config?.options?.jsx;
      return JsxEmit[jsx ?? 0];
    }
  } catch {
    return null;
  }
}

function getTSConfigJSX(filePath: string) {
  return getTsconfig(filePath, 'tsconfig.json', cache)?.config?.compilerOptions?.jsx;
}

function test(name: string, count: number, func: () => void) {
  const start = performance.now();
  for (let i = 0; i < count; i++) {
    func();
  }
  const end = performance.now();

  console.info(`${name} (${count})`, end - start);
}

const TYPESCRIPT = 'using typescript';
const GET_CONFIG = 'using get-tsconfig';

test(TYPESCRIPT, 10, () => getTypescriptJSX(fileURLToPath(import.meta.url)));
test(GET_CONFIG, 10, () => getTSConfigJSX(fileURLToPath(import.meta.url)));

test(TYPESCRIPT, 100, () => getTypescriptJSX(fileURLToPath(import.meta.url)));
test(GET_CONFIG, 100, () => getTSConfigJSX(fileURLToPath(import.meta.url)));

test(TYPESCRIPT, 500, () => getTypescriptJSX(fileURLToPath(import.meta.url)));
test(GET_CONFIG, 500, () => getTSConfigJSX(fileURLToPath(import.meta.url)));

test(TYPESCRIPT, 1000, () => getTypescriptJSX(fileURLToPath(import.meta.url)));
test(GET_CONFIG, 1000, () => getTSConfigJSX(fileURLToPath(import.meta.url)));

test(TYPESCRIPT, 10000, () => getTypescriptJSX(fileURLToPath(import.meta.url)));
test(GET_CONFIG, 10000, () => getTSConfigJSX(fileURLToPath(import.meta.url)));

// console.info(getTSX('/Users/scagood/github/gethooked.io/apps/gethooked-web/src/app/page.tsx'));
```

</details>

Test results:
```
using typescript (10) 16.075999975204468
using get-tsconfig (10) 2.48170804977417
using typescript (100) 50.811582922935486
using get-tsconfig (100) 5.45091700553894
using typescript (500) 161.4930419921875
using get-tsconfig (500) 11.340291976928711
using typescript (1000) 291.0885409116745
using get-tsconfig (1000) 18.019999980926514
using typescript (10000) 2795.298791050911
using get-tsconfig (10000) 159.38912498950958
```

I can confirm that both methods do correctly follow config inheritence.

I am about to head out, so will try to PR later today, or maybe tomorrow 😁

**Comment by scagood** [comment]
I think that is everything covered now?

Shall we close this @aladdin-add, or can you think of something else I need to do?
