### ISSUE TITLE
Use eslint-plugin-es-x instead of eslint-plugin-es.

### ISSUE THREAD

**Issue by ota-meshi** [eslint-community/eslint-plugin-n#12]
I forked [eslint-plugin-es] and released [eslint-plugin-es-x].

https://github.com/ota-meshi/eslint-plugin-es-x

[eslint-plugin-es-x]: https://github.com/ota-meshi/eslint-plugin-es-x
[eslint-plugin-es]: https://github.com/mysticatea/eslint-plugin-es

Do you think `eslint-plugin-n` needs to use [eslint-plugin-es-x]?

**Comment by ota-meshi** [comment]
I don't want to strongly own eslint-plugin-es-x (eslint-plugin-es). I need to use it one so I just want to maintain it. If it's maintained in another community, I think it's good. I will transfer this repository if necessary.

**Comment by aladdin-add** [comment]
sounds a good fit for the eslint-community.
FYI: https://github.com/weiran-zsd/eslint-plugin-node/issues/8.

**Comment by aladdin-add** [comment]
@ota-meshi, are you able to reach @mysticatea? I'd want to take over `eslint-plugin-node`(instead of forking), but have not get response from him .╭(╯^╰)╮

**Comment by ota-meshi** [comment]
I sent a message to him in January about eslint-plugin-node, eslint-plugin-es and regexpp, but I haven't received a reply from him yet 😅.

**Comment by scagood** [comment]
This looks to have been done in #93. Can we close this?
