### ISSUE TITLE
Import and export declarations are not supported yet.

### ISSUE THREAD

**Issue by tedbyron** [eslint-community/eslint-plugin-n#14]
Getting this lint `Import and export declarations are not supported yet. eslint(n/no-unsupported-features/es-syntax)` on a typescript file

node 16.14.2
eslint 8.13.0
eslint-plugin-n 15.1.0

.eslintrc.js:
```js
module.exports = {
  env: {
    browser: false,
    es2021: true,
    mocha: true,
    node: true
  },
  plugins: ['@typescript-eslint'],
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'prettier',
    'plugin:n/recommended'
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 2021,
    sourceType: 'module'
  }
};
```

Any ideas? I saw the plugin checks engine version, my package.json has:
```json
  "engines": {
    "node": ">=16.13.0"
  },
```

**Comment by aladdin-add** [comment]
it's checking `pkg.type` or `.mjs` to see if it's esm in `n/recommended`. But for typescript, you'll need to use `n/recommended-module`.

I think we can document the typescript support at some point.

**Comment by scagood** [comment]
I'm going to close this for now, if you create and include a reproduction, can you re-open it please?
