### ISSUE TITLE
:broom: Remove deprecated rules

### ISSUE THREAD

**Issue by scagood** [eslint-community/eslint-plugin-n#140]
Both `n/no-hide-core-modules` and `n/no-unsupported-features` are deprecated.

We should probably look to remove those rules.

### Participation
- [X] I am willing to submit a pull request for this issue.

**Comment by voxpelli** [comment]
Shall we make a milestone for the next major release and plan it for then?

**Comment by scagood** [comment]
I think that would be good!

Let me know what _should_ be done for these kinda things and I will get on it :grin:

**Comment by voxpelli** [comment]
It for sure has to be removed in a major version, so as soon as such PR is merged we are locked into shipping a new major

And common practice is to let a deprecated rule stay for a minimum amount of releases / time with proper alerts, in case that’s done then feel free to create a PR that clears it up + if you can, create a milestone to track next major (the latter thing is a personal preference of mine, the main maintainers of this package may not agree, but I see no harm in doing it)

**Comment by scagood** [comment]
That makes sense to me!
I know that the docs have said that they've been deprecated for a while.

[no-hide-core-modules](https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/no-hide-core-modules.md) has been deprecated from v4.2.0

[no-unsupported-features](https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/no-unsupported-features.md) has been deprecated from v7.0.0

We're now on v16.3, I would hope that is enough time! :joy:

**Comment by voxpelli** [comment]
Sounds like it’s very much time 😂

**Comment by scagood** [comment]
Based on this comment (https://github.com/mysticatea/eslint-plugin-node/issues/69#issuecomment-285033910) I think we should actually consider not removing the `no-hide-core-modules` rule.

I can see both the use and validity of such problems.
