### ISSUE TITLE
Bug: no-extraneous-import doesn't support import maps

### ISSUE THREAD

**Issue by privatenumber** [eslint-community/eslint-plugin-n#147]
### Environment

Node version: 21
npm version:
ESLint version:
eslint-plugin-n version: v16.4.0
Operating System: macOS

### What rule do you want to report?

no-extraneous-import

### Link to Minimal Reproducible Example

https://eslint-online-playground.netlify.app/#eNp1kDFvwyAQhf+KRVfH3j1371J1KRkwnCJaw9EDqlaR/3sOiCPZUjbu3uPTu3cVkfQ4D19RTEL0dVJtsi4gpU6Kl1kWaYC4WJ9Is4yeDVfpO5bhL4E3UYqp++SpmiYCjc7xHowUPbvCki/WT37cKee+MYKiCPQWkkVfSZVd6dqpD6DIQtlLsagEMTF0c0TMpOH9P0AzODR54XfR1zufeLPn/mRkzhaaCKnlNJjn8vtcv0u/8uVB6W91gcPdrZ89tVRVMgzjVuQ+h4HfVwjleK/tIVFr7smRTTy1Fk+HKh5R1xvHDJTm

### What did you expect to happen?

For it to resolve the package.json import map

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

It only seems to check the dependency objects: https://github.com/eslint-community/eslint-plugin-n/blob/964cf65ff95a5e666037f056a6f27bfde754a758/lib/util/check-extraneous.js#L29-L33

**Comment by scagood** [comment]
Thank you for this report! I think #139 also fixes this (completely by accident) :eyes:

I have added a test and it seems to be covered!

**Comment by privatenumber** [comment]
Oh nice, thank you!

Out of curiosity: if pulling in `enhanced-resolve` to `eslint-plugin-n`, wouldn't there be a significant amount of overlap with https://github.com/import-js/eslint-plugin-import + https://github.com/markjm/eslint-import-resolver-enhanced-resolve ?

In what cases would someone prefer to use the import resolvers in this plugin over `eslint-plugin-import`?

**Comment by scagood** [comment]
mmm, that is a sound point!

I wonder if we should support the import resolver API. :thinking:
I do like the extensibility of that too

**Comment by aladdin-add** [comment]
so can the plugins use the shared settings? sounds interesting! 👍
