### ISSUE TITLE
New Rule: restricted use globals var `__dirname` `__filename` in esm mode

### ISSUE THREAD

**Issue by BobDu** [eslint-community/eslint-plugin-n#164]
### Rule details

restricted use globals var `__dirname` `__filename` in esm mode

These CommonJS variables are not available in ES modules.
https://nodejs.org/api/esm.html#no-__filename-or-__dirname

Suggest use `import.meta.filename` `import.meta.dirname` instead

### What type of rule is this?

Suggests an alternate way of doing something

### Example code

```js
console.log(__dirname);
```

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

**Comment by aladdin-add** [comment]
it's already supported. the globals were only enabled if you were using commonjs: https://github.com/eslint-community/eslint-plugin-n/blob/9613f9b3c410b2a7b6f1d8044c4bec961af5dd53/lib/configs/recommended-script.js#L11-L18

**Comment by scagood** [comment]
🤔 it may be asking for an auto fixer

Something like
```js
import { fileURLToPath } from 'node:url';
const __filename = fileURLToPath(import.meta.url);
```

But that comes with other issues itself 👀

**Comment by BobDu** [comment]
Sorry, I indirectly depend on `eslint-plugin-n` through using `https://github.com/antfu/eslint-config`

It looks like the `rule: no-undef` is not enabled in `@antfu/eslint-config`. I will create a new feature request to that repository.

**Comment by scagood** [comment]
Closed in favour of [`no-undef`](https://eslint.org/docs/latest/rules/no-undef)
