### ISSUE TITLE
Bug: n/no-missing-imports doesn't work correctly for workspace modules

### ISSUE THREAD

**Issue by JeremyLoy** [eslint-community/eslint-plugin-n#184]
### Environment

Node version: 20
yarn version: 4
ESLint version: 8.56
eslint-plugin-n version: 16.6.2
Operating System: MacOS

### What rule do you want to report?

no-missing-imports

### Link to Minimal Reproducible Example

https://github.com/JeremyLoy/hidden-module-import-issue-example/tree/main

### What did you expect to happen?

In this monorepo using yarn workspaces, I have a local package named `@myorg/math`. It is encapsulating an implementation, and only exposing one module via it's package.json `exports` property.

All imports from this package are getting reported as `missing` by eslint-plugin-n, when only the private module `implementation.js` should be getting reported as missing. See the test file for comments.

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

I'm willing to help contribute if you point me in the correct direction!

**Comment by scagood** [comment]
I will take a look at your example at the end of the day (UK time)
I do know that in eslint v17 the resolution mechanisms are completely overhauled ([#139](https://github.com/eslint-community/eslint-plugin-n/pull/139)).

You could try using version 17 (`yarn add -D eslint-plugin-n@next`)

**Comment by JeremyLoy** [comment]
That works, thanks!
