### ISSUE TITLE
wrong rule: n/no-unpublished-import

### ISSUE THREAD

**Issue by its-dibo** [eslint-community/eslint-plugin-n#19]
in my code I use `import { pathsToModuleNameMapper } from 'ts-jest';` but ts-jest is [reported as unpublished](https://github.com/weiran-zsd/eslint-plugin-node/blob/HEAD/docs/rules/no-unpublished-import.md)

I checked all the requirements to consider the package is published
- published in npm and not marked as deprecated
- installed in my node_modules
- doesn't contain files[]
- .npmignore doesn't contain dist/index.js

**Comment by aladdin-add** [comment]
it's warning `'ts-jest'` was used, but not listed in the `pkg.dependencies`. as stated in the docs:

This intends to prevent "Module Not Found" error after npm publish.
💡 If you want to import devDependencies, please write .npmignore or "files" field of package.json.

**Comment by scagood** [comment]
I am closing this, please re-open this if you provide an example :)
