### ISSUE TITLE
rule `shebang` naming

### ISSUE THREAD

**Issue by aladdin-add** [eslint-community/eslint-plugin-n#196]
### eslint-plugin-n version

latest

### What problem do you want to solve?

In the description of the es specification, it is `hashbang` and not `shebang`.

https://github.com/tc39/proposal-hashbang

### What do you think is the correct solution?

renaming rule `shebang` => `hashbang`.

for compat, we could keep `shebang` as an alias.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by scagood** [comment]
I think you're right, we should follow the spec, that being said, I only really knew this as a shebang. I don't like the idea of using an alias though, I would prefer we only used either `hashbang` or `shebang` :eyes:

What do you think?

**Comment by aladdin-add** [comment]
I prefer to maintain compatibility if it doesn't come with too many maintenance costs :).

**Comment by scagood** [comment]
That makes sense to me :)

**Comment by mrhyde** [comment]
Hey, sorry for being late on this, but maybe someone else is wondering the same thing I was "WTH is hashbang?".

I have no idea what TC39 were smoking when they let a dude with zero GitHub activity reach stage 4 but the `#!` thing has always been called a 'SHeBang' since 1980. 
Even Google will try to correct you if you type something like "script hashbang".
So yeah, this was definitely a rushed change...

**Comment by aladdin-add** [comment]
https://github.com/tc39/proposal-hashbang?tab=readme-ov-file#why-hashbang-instead-of-shebang

**Comment by aladdin-add** [comment]
It may indeed be controversial, but we should still follow the terminology of tc39.

**Comment by mrhyde** [comment]
> https://github.com/tc39/proposal-hashbang?tab=readme-ov-file#why-hashbang-instead-of-shebang

https://en.wikipedia.org/wiki/Shebang_(Unix)

Being approved by TC39 does not automatically make it the correct choice. People make mistakes, and this is one example of such a case.

**Comment by aladdin-add** [comment]
As of now, I'm not sure what's the right next step, but`shebang` was not (and will not) removed, it's now an alias of `hashbang`, so you can keep using it. :)
