### ISSUE TITLE
Support ESLint >=9.0.0-beta.1 in peer dependency

### ISSUE THREAD

**Issue by voxpelli** [eslint-community/eslint-plugin-n#197]
### eslint-plugin-n version

17.0.0-3

### What problem do you want to solve?

At a minimal: The range `>=7.0.0` does not include prerelease versions, so it complains when installing this module currently.

### What do you think is the correct solution?

We would need to add `|| >= 9.0.0-beta.1` to the eslint peer dependency (but before that there's maybe something we need to do to adapt to ESLint 9? I didn't find an issue for that)

### Participation

- [x] I am willing to submit a pull request for this change.

**Comment by aladdin-add** [comment]
which package manager are you using? 

For npm>=7, it will auto-install peer-dependencies, you can use `--force` or `--legacy-deps`.

**Comment by voxpelli** [comment]
@aladdin-add Yes, I'm using `npm` and I did use `force` to get around it for now

**Comment by voxpelli** [comment]
@aladdin-add I guess bigger question is: Are we aiming at supporting ESLint 9.x yet?

**Comment by aladdin-add** [comment]
Yes, and it did. see https://github.com/eslint-community/eslint-plugin-n/blob/4778ae86c398f90da13248c2d31bfc4a83cd2dea/.github/workflows/CI.yml#L36

the issue is package managers like npm does not allow prereleases (e.g `9.0.0-beta.1`) for `eslint>=8.0.0`.

**Comment by voxpelli** [comment]
Yeah, I remembered it was added somewhere but became unsure 👍 

> the issue is package managers like npm does not allow prereleases (e.g 9.0.0-beta.1) for eslint>=8.0.0.

Well, its a good thing they don't in most cases, only in the peer dependency field is it annoying

**Comment by voxpelli** [comment]
Reopening as a sister ticket to https://github.com/eslint-community/eslint-utils/issues/183#issuecomment-1987213813

We need to figure out how to set our peer dependency ranges to avoid this
