### ISSUE TITLE
:feather: Use `ts-ignore-import` to lighten the dependencies

### ISSUE THREAD

**Issue by scagood** [eslint-community/eslint-plugin-n#213]
Following up on this comment: [#169 (comment 1546863039)](https://github.com/eslint-community/eslint-plugin-n/pull/169#discussion_r1546863039)

We have decided that it'll be best to use [voxpelli/ts-ignore-import](https://github.com/voxpelli/ts-ignore-import) to be able to mark all types as optional peer dependencies.

Our `peerDependencies` will then look like:
```json
"peerDependencies": {
  "@types/eslint": ">=8"
  "eslint": ">=8"
},
"peerDependenciesMeta": {
  "@types/eslint": {
    "optional": true
  }
}
```

**Comment by voxpelli** [comment]
@scagood You want to do a PR or should I?

**Comment by scagood** [comment]
I want to PR #182 currently, as its got me a second time :sweat_smile:

Could you take this one on?

**Comment by voxpelli** [comment]
@scagood I'll do one right away 👍
