### ISSUE TITLE
Pushed to master :grimacing: 

### ISSUE THREAD

**Issue by scagood** [eslint-community/eslint-plugin-n#230]
@eslint-community/eslint-plugin-node

I have accidentally pushed [`ed7b25c`](https://github.com/eslint-community/eslint-plugin-n/commit/ed7b25cf4ccb3f27bf89993a7fc8c706e3491ad5) to master, can we force push to remove this please :grimacing: 

I am kinda hoping we can enable a branch protection rule to stop this too :sweat: 

Sorry!

**Comment by voxpelli** [comment]
@scagood Also: Are you on eg. Discord? If you join eg. the ESLint Discord then you can ping me really quickly

**Comment by scagood** [comment]
:ok: Can do

I was looking for a force push to keep the change log clean :sweat_smile:
