### ISSUE TITLE
duplicate line with line 135

### ISSUE THREAD

**Issue by aladdin-add** [eslint-community/eslint-plugin-n#248]
duplicate line with line 135

_Originally posted by @alex-kinokon in https://github.com/eslint-community/eslint-plugin-n/pull/169#discussion_r1568122346_

**Comment by scagood** [comment]
Ah, this should be:

```json
  "supported": ">=0.10.0",
  "deprecated": ">=0.10.0"
```

![image](https://github.com/eslint-community/eslint-plugin-n/assets/2230835/3937d56f-57fe-4db4-b840-da9a695cafdd)
