### ISSUE TITLE
Bug: unexpected token ??=

### ISSUE THREAD

**Issue by gaoyuan1223m** [eslint-community/eslint-plugin-n#251]
### Environment

Node version: 18.20.2
npm version: 10.5.0
ESLint version:  7.32.0
eslint-plugin-n version: 16.6.2
Operating System: linux

### What rule do you want to report?

no idea

### Link to Minimal Reproducible Example

no example

### What did you expect to happen?

successful pass eslint

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

![image](https://github.com/eslint-community/eslint-plugin-n/assets/40973672/69a97263-b048-4a98-bdee-b512e9f09be1)

**Comment by aladdin-add** [comment]
it should not happen as `??=` was supported in node.js >=16: https://node.green/#ES2021-features-Logical-Assignment-----basic-support

please re-check your node.js version (try something like `nvm use lts`).

**Comment by scagood** [comment]
I think we should close this unless we get a tangible example 👀
