### ISSUE TITLE
Add checks for logical assignment operator

### ISSUE THREAD

**Issue by binyamin** [eslint-community/eslint-plugin-n#26]
- [TC39 Proposal](https://github.com/tc39/proposal-logical-assignment/)
- As per [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment#browser_compatibility), it was introduced in Node.js v15.0.0

**Example**
```js
let myVar = null; // or `undefined`
myVar ??= "defined";
```

**Comment by aladdin-add** [comment]
not sure I have gotten your point. can you explain a bit more "add checks"?

**Comment by aladdin-add** [comment]
should be addressed in https://github.com/eslint-community/eslint-plugin-n/releases/tag/16.5.0.
