### ISSUE TITLE
Bug: The 'Buffer' is still an experimental feature The configured version range is '>=18.6'.

### ISSUE THREAD

**Issue by coderaiser** [eslint-community/eslint-plugin-n#265]
### Environment

Node version:
npm version:
ESLint version:
eslint-plugin-n version:
Operating System:
Latest

### What rule do you want to report?

n/no-unsupported-features/node-builtins

### Link to Minimal Reproducible Example

https://github.com/coderaiser/putout/actions/runs/8982632006/job/24670666707#step:7:24

### What did you expect to happen?

<img width="1071" alt="image" src="https://github.com/eslint-community/eslint-plugin-n/assets/1573141/0b216b97-4522-4edf-95a6-e264c05ea1ce">

I have such code examples in `README.md`:

```js
new Buffer(123);
new Buffer(n);
new Buffer('hello');

new Buffer([]);
new Buffer(buf);
```

Looks like it is not `experimental` but `deprecated` syntax according to [DEP005](https://nodejs.org/api/deprecations.html#deprecations_dep0005_buffer_constructor)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by scagood** [comment]
How curious, its marked as deprecated:
https://github.com/eslint-community/eslint-plugin-n/blob/master/lib/unsupported-features/node-builtins-modules/buffer.js#L25-L26
