### ISSUE TITLE
Change Request: Add option to allow `NODE_ENV` in `n/no-process-env`

### ISSUE THREAD

**Issue by alecmev** [eslint-community/eslint-plugin-n#283]
### eslint-plugin-n version

17.7.0

### What problem do you want to solve?

It's common for bundlers to inline `process.env.NODE_ENV` and such, so that minifiers can do their job and eliminate dead code. Currently `n/no-process-env` takes issue with every use of `process.env.NODE_ENV` and I have to disable it manually. I don't want to disable it completely as I still want to encourage configuration validation. I can't import `nodeEnv` from `./config.js` or something because some (all?) minifiers don't dig that far and will not eliminate any code wrapped in `if (nodeEnv === "production") ...`.

### What do you think is the correct solution?

Options:

1. Add `allowNodeEnv`, defaulting to `false`. Probably a bit simpler to implement and covers the majority of cases.
2. Add `allowlist`, defaulting to `[]`. `NODE_ENV` is the behemoth, but [there's a long tail of other variables](https://github.com/vercel/next.js/blob/b4eff7020bfe9a2fe0dae9c65155bd4b21a48fe6/packages/next/src/build/webpack/plugins/define-env-plugin.ts#L159-L261).

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by scagood** [comment]
It sounds to me like you may be better off disabling the rule in general if you have a long list of variables you want to use 🤔

**Comment by alecmev** [comment]
I personally don't have a long list, just `NODE_ENV` 😄 So would be happy with `allowNodeEnv`. I mention other variables because who knows what others might want to allow.

**Comment by scagood** [comment]
Ah, I see!

Looking at the source, it looks like we only look for the `process.env` (https://github.com/eslint-community/eslint-plugin-n/blob/master/lib/rules/no-process-env.js#L11-L16), I wonder if we should add a check to look for th what property on `process.env` is called, or only report the use of specific env vars 🤔

**Comment by voxpelli** [comment]
> Add allowlist, defaulting to []

This is what I would add. Good suggestion!
