### ISSUE TITLE
Repository author/sponsor settings

### ISSUE THREAD

**Issue by nazrhyn** [eslint-community/eslint-plugin-n#30]
![image](https://user-images.githubusercontent.com/1672405/174197334-72799943-5f2d-40d5-b843-69b45f56b4ff.png)

I'm not sure what configures this, but I'm still seeing the sponsor prompt for **mysticatea** on this repository.

**Comment by aladdin-add** [comment]
I have not set a github sponorship. let's just set a new one util moving to the new home @eslint-community.

related: https://github.com/eslint/rfcs/pull/91

**Comment by MichaelDeBoey** [comment]
Let's hope, we can transfer the original repo asap to the new @eslint-community org 🙏

https://github.com/mysticatea/eslint-plugin-node/issues/341

**Comment by uiolee** [comment]
Looks like the issue has been solved.
