### ISSUE TITLE
Bug: TS type error in index.d.ts

### ISSUE THREAD

**Issue by ox-cc-fspd** [eslint-community/eslint-plugin-n#316]
### Environment

Node version: 20.9.0
npm version:
ESLint version: 9.x
eslint-plugin-n version: 17.10.0
Operating System: Win11

### What rule do you want to report?

all rules

### Link to Minimal Reproducible Example

-

### What did you expect to happen?

I am using a TypeScript wrapper around this plugin.

Using v17.10.0 gives TS type errors, because the index.d.ts does not contain a declaration for type `Configs` anymore, as there was in v17.9.0. There is only a JSDoc type declaration which does not help in a real TS env.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by scagood** [comment]
Can you link to a repo or make a quick playground example of this being an issue please?

**Comment by scagood** [comment]
This looks to be a ts 5.5 issue, as things start to work again in ts 5.4.

This screams that we need [Type coverage](https://github.com/eslint-community/eslint-plugin-n/issues/212) :thinking:

**Comment by danielrentz** [comment]
Thanks for the quick fix!
