### ISSUE TITLE
Eslint 9 support

### ISSUE THREAD

**Issue by aclarembeau** [eslint-community/eslint-plugin-n#321]
### Environment

Hello team, and thank you for the wonderful work you've done maintaining this plugin. 
I was wondering: do you have any plan to add compatibility for eslint9+? I see in the package.json that this plugin only works with eslint 8 

Thank you 

### What rule do you want to report?

none

### Link to Minimal Reproducible Example

none

### What did you expect to happen?

none / just a question

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by scagood** [comment]
Oh, this is just a package.json issue!
We already test against eslint v9 (https://github.com/eslint-community/eslint-plugin-n/blob/master/.github/workflows/CI.yml#L35)
