### ISSUE TITLE
no-unspported-features support new added node.js globals

### ISSUE THREAD

**Issue by aladdin-add** [eslint-community/eslint-plugin-n#35]
e.g. `fetch`: requires node.js >= 18.0.0

**Comment by scagood** [comment]
We now use eslint-plugin-es-x. Is this issue resolved? 👀

**Comment by aladdin-add** [comment]
not yet. `fetch` was enabled in globals, but the rule `no-unspported-features` needs to report if it was not supported in the given node.js versions: https://github.com/eslint-community/eslint-plugin-n/blob/master/lib/rules/no-unsupported-features/node-builtins.js#L17C15-L26

**Comment by scagood** [comment]
I wonder if we should try to pull this information from https://nodejs.org/api/all.json

I can't imagine it'd be too hard to convert the basic data. The deprecations and experimental data may be a little harder.

**Comment by scagood** [comment]
This can be closed (I hope :sweat_smile:) due to #174
