### ISSUE TITLE
Bug: no-sync fail positive

### ISSUE THREAD

**Issue by RebeccaStevens** [eslint-community/eslint-plugin-n#354]
### Environment

Node version: 22.9.0
npm version: 10.8.3
ESLint version: 9.12.0
eslint-plugin-n version: 17.11.0
Operating System: Nobara 40

### What rule do you want to report?

no-sync

### Link to Minimal Reproducible Example

https://eslint-online-playground.netlify.app/#eNp9UE1PwzAM/SuWT5u0dRLiVMQNfgFHzCFK3aqQOlE+pk1V/ztJ08G4cHFi+/m9Z88YvD7xRU3OcPMZsMVxctZHmOG171lHWKD3dgJCXnPCJxISbSVEOCuTGJ43aOOTvF1F70jgVgpJa+Zu9/iwJ9nnUTwgBzNKbDJFPw5/ROVHa4UcnUnDKEfZRPmyojruVTIR3ovOXAJARYY2+xZYDrXok+FSqhlkXjmJPYbskbAtMt5bT1j7S3ly+KgundJfaihHsZIdriSE8eq4zk62y/SEqxZhx+cXdiwdix45FMym+3u5MmZU5JD/m8Xbqv827+5wj9r8Lrh8Ax6jlbM=

### What did you expect to happen?

No error, as `Effect.runSync` is not part of the node api.

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

I've got a package that you can use to detect where types are coming from: [ts-declaration-location](https://github.com/RebeccaStevens/ts-declaration-location)

With this, you can make it so only types from `@types/node` are marked as violations.
Note: this package is also being used by [eslint-plugin-functional](https://github.com/eslint-functional/eslint-plugin-functional).

**Comment by scagood** [comment]
mmm, the rule was not meant to detect only node APIs, it was meant to detect anything that could be synchronous 🤔

The only test for this rule is effectively this selector:

https://github.com/eslint-community/eslint-plugin-n/blob/23d0e846e9dbfb68ccf7f410a83457514d432263/lib/rules/no-sync.js#L7-L14

**Comment by scagood** [comment]
🤔 I wonder if we should add an `ignores` to this rule too. 

I noticed a similar thing here: https://github.com/eslint-community/eslint-plugin-n/issues/341#issuecomment-2364739666

**Comment by aladdin-add** [comment]
👍 to adding a new option `ignores`.
