### ISSUE TITLE
:boat: Port the codebase to typescript

### ISSUE THREAD

**Issue by scagood** [eslint-community/eslint-plugin-n#371]
> This makes me think that we should port the codebase to pure TS at one point in the (near) future 🤔
>
> CC/ @eslint-community/eslint-plugin-node

_Originally posted by @MichaelDeBoey in https://github.com/eslint-community/eslint-plugin-n/pull/367#pullrequestreview-2404893785_

**Comment by scagood** [comment]
> > This makes me think that we should port the codebase to pure TS at one point in the (near) future 🤔
> 
> I am currently in the jsdoc > typescript camp for a few reasons:
> 1. Any transform cause more problems in the future than they solve now
> 1. I prefer adding documentation lines to functions, meaning I have to make a jsdoc block anyway
> 1. The `allowJs` flag means that we can use all of typescript's typing benefits without the transpilation step.
> 
> Its not that I am not against using typescript, I just find that I prefer jsdoc :thinking:

_Originally posted by @scagood in https://github.com/eslint-community/eslint-plugin-n/pull/367#issuecomment-2447204689

**Comment by voxpelli** [comment]
I'm fully with @scagood on this – I see no reason to swap JSDoc for TS syntax – they are both first class syntaxes supported by the TypeScript type checker

**Comment by scagood** [comment]
I wanted to add some pros for `typescript` here so things are a little balanced:
1. Making advanced types in `JSDoc`, while possible is sometimes cumbersome.
2. Integrations with IDEs when using `typescript` directly is a little smoother (eg autocompletion of types in `JSDoc` blocks)
3. `typescript` + `JSDoc` feels like a second class citizen in a few cases. For example:
    - the `@import` tag does not work if there is not already at least one import.
    - #320 Almost certainly would not have happened in full typescript

**Comment by scagood** [comment]
@aladdin-add @MichaelDeBoey 

What do you think either way?

**Comment by aladdin-add** [comment]
I like typescript + jsdoc: easier to write some advanced types, and no build needed just like before. 😄

**Comment by MichaelDeBoey** [comment]
> https://github.com/eslint-community/eslint-plugin-n/issues/320 Almost certainly would not have happened in full typescript

It's exactly for these kind of things that I think having this build step makes more sense

**Comment by voxpelli** [comment]
Bugs can happen anywhere in the TS type declaration generation.

If we want to guard against it then we should either manually create the type declarations or add tests for the generated ones.

---

We can actually remove the type declaration generation from this plugin as the only types that gets uploaded and used are the 5-10 lines of `types/index.d.ts`

The internal type checking is the more important and useful one.

**Comment by aladdin-add** [comment]
@voxpelli - it's just i did in https://github.com/eslint-community/eslint-plugin-n/pull/366.

it split the two things:

1. committed a user defined `index.d.ts` - for users.
2. make `tsc` just do type-checking - for devs.

**Comment by scagood** [comment]
I am not sure I agree that because that problem was simply mitigated that was should dismiss it as not a problem :thinking: 

---

I do however think that we should test the `index.js` interface, especially as that will cause the exported types to be tested too.

**Comment by scagood** [comment]
🤔 I think I am going to close this as 'not doing'
