### ISSUE TITLE
✨ Node v23.3.0 support

### ISSUE THREAD

**Issue by MichaelDeBoey** [eslint-community/eslint-plugin-n#389]
Deprecated:

- [`util.getCallSite`](https://nodejs.org/docs/latest/api/util.html#utilgetcallsitesframecountoroptions-options)

Experimental:

- [`util.getCallSites`](https://nodejs.org/docs/latest/api/util.html#utilgetcallsitesframecountoroptions-options)

Supported:

- [`process.report.excludeEnv`](https://nodejs.org/docs/latest/api/process.html#processreportexcludeenv)

**Comment by scagood** [comment]
We also need to deprecate/remove `util.getCallSite` as:
https://github.com/eslint-community/eslint-plugin-n/blob/master/lib/unsupported-features/node-builtins-modules/util.js#L97

> `util.getCallSite` -> `util.getCallSites`
> https://nodejs.org/docs/v23.3.0/api/util.html#utilgetcallsitesframecountoroptions-options

**Comment by MichaelDeBoey** [comment]
@scagood Good catch!
