### ISSUE TITLE
why is  n/file-extension-in-import a stylic?

### ISSUE THREAD

**Issue by jimmywarting** [eslint-community/eslint-plugin-n#39]
i don't consider  file extension as something that is stylic
it's more of a problem if you want to trully run ESM scripts that demands that you use file extension

it will possible only work b/c someone is using a build script anyways.
i think demanding a extension should be a recommended rule.
when using remote path resolver like http import you can't guess what you meant to import cuz you do not have access to the fs

https://nodejs.org/dist/latest-v18.x/docs/api/esm.html#mandatory-file-extensions (<-- **mandatory** is in the link desc)
https://github.com/standard/standard/issues/1674

**Comment by aladdin-add** [comment]
I agreed it's more like an "possible errors" rule. it's just the original implemention a few yerars ago.

**Comment by aladdin-add** [comment]
well, I think it's time to rethink the rule. It was written when the node.js esm was not stabilized. Nowadays it's stabilized in node v12. time to make some changes.
1. renaming to `file-extension`, and also check requires(common.js). the rule was only checking imports. but some devs may still  want to use file extensions for some reasons. 

2. more configurable:
```js
"n/file-extension-in-import": [2, { "requires": "always", "imports": "always"}
```

3. recommended preset changes:

    a. recommended-script:

```js
"n/file-extension-in-import": [2, { "requires": "never"}
```

    b. recommended-module:

```js
"n/file-extension-in-import": [2, { "requires": "always", "imports": "always"}
```

**Comment by aladdin-add** [comment]
do you mean the `meta.docs.category`?
https://github.com/weiran-zsd/eslint-plugin-node/blob/d7b975a07e1b876ca2c75597d054a81564b25685/lib/rules/file-extension-in-import.js#L40

it's not actually used anywhere, and eslint has removed it in all its core rules.

**Comment by jimmywarting** [comment]
I think both of `import(x)` and `require(x)` should by default require file extensions

It don't hurt to use extension in CommonJS too. in fact it makes things faster to lookup and also easier for build tools to not having to 2nd guess what you meant to import. it only complicates things further and they need to apply to the same rule as node.js resolve algoritm over at: https://nodejs.org/dist/latest-v18.x/docs/api/modules.html#all-together (which is just insane)
Ryan dhal regretted all of it and it is not how the web/esm works.

more and more ppl are switching over to esm and refactor cjs to esm is no easy task as just simply switching out all `require` calls to `import()` and using the same path. it needs to solve the path to `index.js` as well if things where just `require('./index.js')` then it would be as simple as just changing it to an `import` statement and an auto fix would be easier to write.

After reading [The cost of many small modules](https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/) i made a bench test that tried to require many files with and without file extension and using index.js vs just a normal name such as mod.js
And the script loaded faster if the path was more explicit as it did not have to stat files/folder to look up as many files to quickly figuring out what you ment to import

**Comment by jimmywarting** [comment]
any progress on this part? would like to resolve https://github.com/standard/standard/issues/1674 but are a bit blocked

**Comment by scagood** [comment]
If we want to convert `n/file-extension-in-import` to a recommended rule, can we create another issue for this please? 🙏
