### ISSUE TITLE
Bug: In the no-unsupported-features/node-builtins rule, certain module names containing "/" cannot be properly suppressed.

### ISSUE THREAD

**Issue by sunafterrainwm** [eslint-community/eslint-plugin-n#395]
### Environment

Node version: v20.14.0
npm version: pnpm 9.15.0
ESLint version: 9.16.0
eslint-plugin-n version: 17.14.0
Operating System: Windows 10

### What rule do you want to report?

no-unsupported-features/node-builtins

### Link to Minimal Reproducible Example

https://eslint-online-playground.netlify.app/#eNpVUdtOwzAM/RUrLwWJdoXHInjiL8geQuOWQOpEuYyhqf9O0mQbS6TIsY+P7eMT827c4VEsVmP35dnA1GKNC3ACP36ijBodrDA5s0BDRuIQ1ILO72zyKI++eeYkfoQKV3yXv3fw2Pc93Kcwe2DotaLQjYYmNd/UocpdEK3VcVbUUqblhMcNI3ESUQd45wRwyg9AAfohNUqwPhSnS+Wzq/wgdbwj00by0WYilO2EIkSHPvklth9R6ZBYmqFw1yx0zrimcuZzIcznkMZXhgZoXl/gqe/S/Y8FUDOZVCJxQlPU6s5qdbciNbC/Jp6HANhXq3jyuy8yWjF+izkvylCScGuLs/BrkbMhWYvJ3JxteZxJPLyhRZJIo0KfMXUSXjdS0rQI6JNdy56Dl2XcoraeOK1s/QMeqrbs

### What did you expect to happen?

According to the [documentation](https://github.com/eslint-community/eslint-plugin-n/blob/HEAD/docs/rules/no-unsupported-features/node-builtins.md#ignores), the `ignores` array should include the value displayed in the name field of the error message, `timers/promises.scheduler.wait`. However, it is not possible to use this value in the configuration file. Upon inspecting the rule schema, it is found that only `timers.promises.scheduler.wait` is allowed.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by scagood** [comment]
Thank you for the report! 

My immediate though is that this is the recursion prevention :thinking:

Specifically this one:
https://github.com/eslint-community/eslint-plugin-n/blob/master/lib/util/enumerate-property-names.js#L26-L28

Because the scheduler is already seen before in the option you've mentioned: `timers.promises.scheduler`
