### ISSUE TITLE
`Buffer.slice` is deprecated

### ISSUE THREAD

**Issue by jimmywarting** [eslint-community/eslint-plugin-n#40]
It was bad that they overrided it in the first place...
https://nodejs.org/dist/latest-v18.x/docs/api/buffer.html#bufslicestart-end

Buffer don't even have a slice method that did the correct thing. slice is only an alias for subarray. and subarray is what ppl should have been using instead.

**Comment by aladdin-add** [comment]
PRs are welcome! 👍

**Comment by aladdin-add** [comment]
Is this still an issue? @scagood

**Comment by scagood** [comment]
I think it's a great thing to do... But I am not sure about the feasibility of it.

I think it'd be great to track the prototypal depreciation and support, but I am starting to think it may be a little too hard 😔

**Comment by aladdin-add** [comment]
Well, let's just document its limitations, and close this one. :)

**Comment by scagood** [comment]
Yeah, agreed.
