### ISSUE TITLE
Report for features that are not available for the provided engines range

### ISSUE THREAD

**Issue by kiranparajuli589** [eslint-community/eslint-plugin-n#43]
### Description
I have a node-check repository here at [repo-link](https://github.com/kiranparajuli589/node-check). The project is using NodeJS `>=8.0.0 <=14.20.0` properly configured at the `engines` inside the `package.json` file. 

### What I want to achieve
Now, sometimes we may accidentally add NodeJS code that is not supported in the specified range but available with the latest versions, like while using `replaceAll` with strings. It is only introduced in v15, so if the range does not include `15.x.x`, the code will break.

Can `eslint-plugin-node` help me in this case? Can we configure this package to report for such issues?

### Demonstration of the Problem
Here is a Github workflow demonstrating the case: https://github.com/kiranparajuli589/node-check/runs/7738971827?check_suite_focus=true

Here I've used `plugin:n/recommend` in the extends section, but the linter does not report anything :(

**Comment by aladdin-add** [comment]
yes, we had a rule [no-unsupported-features/es-builtins](https://github.com/weiran-zsd/eslint-plugin-node/blob/master/docs/rules/no-unsupported-features/es-builtins.md) for such purpose. But it has not been updated to check the new added es features.

related: #35

**Comment by kiranparajuli589** [comment]
The docs says:
> :star: This rule is included in plugin:n/recommended preset.
And, I've used the `plugin:n/recommend` inside Eslint `extends` array. But why this is not reporting for my case. Is my configuration correct?

**Comment by aladdin-add** [comment]
under the ground, it used [eslint-plugin-es](https://www.npmjs.com/package/eslint-plugin-es) to do so. but it's no longer actively maintained. A workaround is to use its maintained fork: https://www.npmjs.com/package/eslint-plugin-es-x

**Comment by aladdin-add** [comment]
https://github.com/ota-meshi/eslint-plugin-es-x/blob/master/docs/rules/no-string-prototype-replaceall.md

**Comment by kiranparajuli589** [comment]
Thank you for the refs. IMHO, this only targets for `replaceAll`, or we've to specify specific rules to avoid specific `unsupported` usages. Is this the only way? Or, can we just make it grab/report all unsupported code usages?

**Comment by scagood** [comment]
Mmm, we now use eslint-plugin-es-x. Is this issue resolved? 👀

**Comment by scagood** [comment]
We need to go through and update [lib/rules/no-unsupported-features/es-syntax.js](https://github.com/eslint-community/eslint-plugin-n/blob/master/lib/rules/no-unsupported-features/es-syntax.js)
