### ISSUE TITLE
Update default node engine version

### ISSUE THREAD

**Issue by remcohaszing** [eslint-community/eslint-plugin-n#45]
At the moment of writing, the latest supported Node.js version is 14 ([release schedule](https://github.com/nodejs/Release#release-schedule)). Currently the default version in this plugin is Node.js 8, which reached end of life in 2019. I think it makes sense to update the default version.

**Comment by aladdin-add** [comment]
yes, I think we could update it in v16. related: #42

**Comment by remcohaszing** [comment]
This was resolved by #91.
