### ISSUE TITLE
Allow setting the Node.js version in shared settings

### ISSUE THREAD

**Issue by jordanbtucker** [eslint-community/eslint-plugin-n#46]
Currently, the only way to specify the target node version is by setting the `engines.node` field in `package.json` or by specifying a `version` field in each rule configuration.

It would be helpful to be able to set the version in shared settings like you can set `allowModules`, `convertPath`, and `tryExtensions`.

This would allow you to set the Node.js version for a specific directory, like `test`.

```jsonc
// package.json
{
  "engines": {
    "node": "^12 || >=14"
  }
}
```

```jsonc
// test/.eslintrc.json
{
  "settings": {
    "node": {
      "version": ">=14"
    }
  }
}
```

Let me know if this is desirable, and I can work on a PR.

**Comment by aladdin-add** [comment]
sure, please feel free to send a PR!

**Comment by privatenumber** [comment]
Another use-case would be for shareable configs to raise the default Node.js version from v8.
