### ISSUE TITLE
Support package exports in file-extension-in-import

### ISSUE THREAD

**Issue by DMartens** [eslint-community/eslint-plugin-n#50]
It seems [package entry points](https://nodejs.org/dist/latest-v18.x/docs/api/packages.html#package-entry-points) are not supported by `file-extension-in-import` as it still requires a file extension for them, eg. for `eslint/use-at-your-own-risk`.
But by adding the file extension the file in the package root is required instead.
I am willing to submit a pull request for this.

**Comment by aladdin-add** [comment]
I was able to repro, thanks for the report!

**Comment by kidonng** [comment]
#21 might be related.

**Comment by scagood** [comment]
You're right here, this is a duplicate of #21
