### ISSUE TITLE
`resolvePaths` option works differently with `import` compared to `require`

### ISSUE THREAD

**Issue by jordanbtucker** [eslint-community/eslint-plugin-n#56]
When using the `resolvePaths` setting to set the paths where eslint should look when resolving module specifiers, `import` statements resolve as expected, but `require` statements don't.

See my [minimal reproducible example](https://github.com/jordanbtucker/eslint-plugin-n-resolve-issue).

The way eslint-plugin-n handles `import` statements is that it pretends that the source module is in [each](https://github.com/eslint-community/eslint-plugin-n/blob/3e273edb412874df1d61b06bdf537d8765e7c305/lib/util/import-target.js#L29) of the directories specified by `resolvePaths`, however it [does not do this](https://github.com/eslint-community/eslint-plugin-n/blob/3e273edb412874df1d61b06bdf537d8765e7c305/lib/util/import-target.js#L52) for `require` statements.

---

Note that the `paths` property of the `options` parameter of `resolve.sync` should work like the `paths` property of the `options` parameter of [`require.resolve`](https://nodejs.org/docs/latest-v14.x/api/modules.html#modules_require_resolve_request_options), but it [doesn't](https://github.com/browserify/resolve/issues/188).

**Comment by scagood** [comment]
#139 has just been merged which may help with this as both import and require use the same code 😀
