### ISSUE TITLE
type import flagged is missing and unpublished

### ISSUE THREAD

**Issue by NullVoxPopuli** [eslint-community/eslint-plugin-n#66]
idk if there is an existing rule to handle this case, but in Typescript, you can do:
```ts
import type { SomeType } from 'some-library';
```

for context, when transpiling to either CJS or MJS, the import doesn't make it to the output -- obviously a lint plugin can't know that is going to happen, but if there could be some way to relax `n/no-missing-import` and `n/no-unpublished-import`, (or require that `some-library` be in `devDependencies` if not found in the normal locations, this'd be a huge help <3

**Comment by aladdin-add** [comment]
I'm open to that - just wondering what's the best solution on it. the generated `.d.ts` still requires `some-library`, so will it break the the lib's users running `tsc`(if using ts)?

**Comment by scagood** [comment]
We do have an option for ignoring type imports in `no-unpublished-import` [ignoreTypeImport](https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/no-unpublished-import.md#ignoretypeimport)

Does this cover your use case?

**Comment by BrummbaerFr** [comment]
I am running into the exact same problem, using a private package that only exports types.

`ignoreTypeImport` does fix the problem for `no-unpublished-import`, however I had to just disable for `no-missing-import` for the problematic line.

**Comment by scagood** [comment]
mmm, could you possibly reproduce the issue in a small repo or in the [eslint playground](https://eslint-online-playground.netlify.app/)?

**Comment by BrummbaerFr** [comment]
> mmm, could you possibly reproduce the issue in a small repo or in the [eslint playground](https://eslint-online-playground.netlify.app/)?

Sure! Here it is: [eslint-n-missing-import-repro](https://github.com/BrummbaerFr/eslint-n-missing-import-repro/tree/main)

**Comment by scagood** [comment]
That's perfect, thank you so much! 💚

I will try to look in the latter half of this week

**Comment by scagood** [comment]
I am thinking about trying to change from [import-meta-resolve](https://www.npmjs.com/package/import-meta-resolve) to [enhanced-resolve](https://www.npmjs.com/package/enhanced-resolve) 🤔

There are a few reasons for this:
1. You can just use `require()` to import it, unlike currently where we use a built version of `import-meta-resolve`
2. It provides a mechanism to implement the ts `paths` aliases (#84)
3. This allows us to pass `extensionAlias` into the resolver (#134)
4. This allows us to handle different file extension (#33)

This could be a little finicky to get right 😅 I will give it a go this weekend to see if its plausible!
