### ISSUE TITLE
`no-missing-imports` don't support dependencies subpaths

### ISSUE THREAD

**Issue by piranna** [eslint-community/eslint-plugin-n#75]
If an import includes a sub-path, like `@scope/package-name/sub-path`, it's identified as missing. Not sure if in all the cases, or just only when using the `exports` field, but in any case it should be easy to fix, get the package sub-path and checks if it exists in the package folder or matches its `exports` field.

**Comment by NullVoxPopuli** [comment]
I just ran in to this, too. gonna disable the rule for now 🙃

**Comment by SBoudrias** [comment]
The #4 PR seems to imply this should now work the same as the selected Node.js version 🤔 

But I'm running into the same issue with `imports` inside `package.json` pointing to polyfills of `#prefixed` packages.

**Comment by piranna** [comment]
I've just found `n/no-missing-import` doesn't works with scoped packages at all, not sure if it's a bug or a regression.

**Comment by scagood** [comment]
Hopefully this is resolved now due to #132

**Comment by scagood** [comment]
I am going to assume that this is resolved, and thus I will close this issue.

Please re open it if you still have this issue!
