### ISSUE TITLE
Rule suggestion: prefer `node:` prefixed imports when possible

### ISSUE THREAD

**Issue by thernstig** [eslint-community/eslint-plugin-n#77]
Older built-in Node modules such as fs now can be imported via either their name or node: + their name:

```js
import fs from "fs";
import fs from "node:fs";
```

The prefixed versions are nice because they can't be overridden by user modules and are similarly formatted to to prefix-only modules such as node:test.

Suggestion: let's add a linter rule to enforce using them, with an auto-fixer.

(copied from https://github.com/mysticatea/eslint-plugin-node/issues/344)

**Comment by aladdin-add** [comment]
yes, good to have. 👍

**Comment by voxpelli** [comment]
There is a rule like this in `eslint-plugin-unicorn`, maybe we can ask to copy/lift that over? https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-node-protocol.md

**Comment by thernstig** [comment]
A general question: Would such a rule be better in https://github.com/import-js/eslint-plugin-import?

I resorted to using `eslint-plugin-unicorn` for that rule right now, but it feels like a nice rule to have in here or https://github.com/import-js/eslint-plugin-import.

**Comment by gurgunday** [comment]
I think it should be here as well

**Comment by gurgunday** [comment]
Can we cut a release?

CC @aladdin-add

**Comment by aladdin-add** [comment]
We are in the development of the new major v17. I'll try to port it to v16 later.
