### ISSUE TITLE
Long term home of `eslint-plugin-n`

### ISSUE THREAD

**Issue by voxpelli** [eslint-community/eslint-plugin-n#8]
As discussed in a previous thread with eg. me, you @aladdin-add, @MichaelDeBoey: https://github.com/standard/eslint-config-standard/issues/192#issuecomment-996588999

Having an `eslint-community` organization (or similar) that's home to this module + `eslint-plugin-promise` and other important modules would be good .

@aladdin-add You mentioned that @nzakas were setting up an `eslint-community` organization, do you know anything more?

**Comment by MichaelDeBoey** [comment]
Would be lovely if we could move [`eslint-plugin-node`](https://github.com/mysticatea/eslint-plugin-node), [`eslint-plugin-es`](https://github.com/mysticatea/eslint-plugin-es), [`eslint-utils`](https://github.com/mysticatea/eslint-utils), [`@mysticatea/eslint-plugin`](https://github.com/mysticatea/eslint-plugin) & [`eslint-plugin-promise`](https://github.com/xjamundx/eslint-plugin-promise) to this new org too

**Comment by nzakas** [comment]
There’s nothing more to report right now. We’ve got some other higher priority tasks I need to work on first. Stay tuned to the blog and Twitter for updates.

**Comment by MichaelDeBoey** [comment]
@nzakas If there's some work we can take out of your hands, I'm happy to help out!

**Comment by voxpelli** [comment]
`eslint-community` is mentioned in https://github.com/eslint/eslint/issues/15383

**Comment by MichaelDeBoey** [comment]
It seems like they agreed to not make it a priority: https://github.com/eslint/eslint/issues/15383#issuecomment-1026524423 🤔

**Comment by aladdin-add** [comment]
However, I did not see it was discussed in the [meeting](https://github.com/eslint/tsc-meetings/blob/main/notes/2022/2022-01-27.md#roadmap-planning-2022). :-( 

Anyway, the only thing is to write a RFC to talk about how it runs: https://github.com/eslint/rfcs

**Comment by thernstig** [comment]
Definitely go for `eslint-community` once its been setup by ESLint maintainers, it will give it a well-known home :)

Then it can live in npm under @eslint/eslint-plugin-node possibly.

**Comment by nazrhyn** [comment]
Keeping the name via a namespace like that would be awesome, as well as having these under an org. Looking forward to the changes!

**Comment by voxpelli** [comment]
Created a discussion around this in the ESLint repo: https://github.com/eslint/eslint/discussions/15929

**Comment by voxpelli** [comment]
And now an RFC regarding this is up: https://github.com/eslint/rfcs/pull/91

**Comment by MichaelDeBoey** [comment]
Let's hope, we can transfer the original repo asap to the new @eslint-community org 🙏

https://github.com/mysticatea/eslint-plugin-node/issues/341

**Comment by thernstig** [comment]
Would it be time to consider that https://github.com/mysticatea/eslint-plugin-node (see https://github.com/mysticatea/eslint-plugin-node/issues/341)  will not be transfered? And instead transfer this repo?

**Comment by MichaelDeBoey** [comment]
@thernstig We're working on transferring @mysticatea's repos one at a time

**Comment by aladdin-add** [comment]
a few months passed, but we are still not able to transfer the original repo( we have not gotten response from @mysticatea  😢). I think it's time to make the new @eslint-community/eslint-plugin-node.

I have the following plans:
1. checkout a new branch from the original main.
2. pick all the features/bugfixes
3. transfer the opened issues/PRs to the new repo
4. review & merge the PRs
5. release @eslint-community/eslint-plugin-node v1.0
6. make the eslint-plugin-n as an alias of the new package (DX matters! 😄 )


questions:
* does anyone have the admin access to https://github.com/mysticatea/eslint-plugin-node, please add me. cc @ota-meshi 
* how can I get the publish access to `@eslint-community/eslint-plugin-node`? cc @MichaelDeBoey

**Comment by nazrhyn** [comment]
I think the horizontal name changes happen regularly enough (e.g. `apollo-server` -> `@apollo/server`) that `eslint-plugin-node` -> `@eslint-community/eslint-plugin-node` makes sense. Even makes it seem "official", which is probably good.

**Comment by voxpelli** [comment]
@aladdin-add I think we should keep working in this repo unless we can move the original repo here

I am pro on renaming this repo to `eslint-plugin-node`

I think this issue should be considered resolved when https://github.com/eslint-community/eslint-plugin-n/issues/55 is resolved

**Comment by scagood** [comment]
As #55 is closed shall we close this?

**Comment by voxpelli** [comment]
@scagood Yeah, I think a rename to `@eslint-community/eslint-plugin-node` or such is a bit late to do now anyway and out of scope of this issue
