### ISSUE TITLE
feat request: missing-callback

### ISSUE THREAD

**Issue by yfdyh000** [eslint-community/eslint-plugin-n#82]
I hope this is a real issue.
I recently modified like `fs.unlinkSync` to `fs.unlink` but missing the callback parameter ``callback: fs.NoParamCallback``, I mistakenly think it is an optional parameter. No editor or building message appears, an error occurs when it is executed, even quietly if meet `try catch`.

**Comment by voxpelli** [comment]
I think this might maybe be better solved by adopting some kind of typing, see eg https://github.com/voxpelli/types-in-js

Not saying this module shouldn't support this, but I personally would opt to solve this through type checking

**Comment by aladdin-add** [comment]
I also agreed this kind of issues is in the scope of something like ts.
