### ISSUE TITLE
n/shebang has wrong entry for report node

### ISSUE THREAD

**Issue by Zamiell** [eslint-community/eslint-plugin-n#85]
The bug is here:

https://github.com/eslint-community/eslint-plugin-n/blob/master/lib/rules/shebang.js#L164

Instead of selecting `node`, we need to select only the first line of the file.
In other words, when in VSCode:
- When the shebang is there and it is not supposed to be, we want the yellow squiggly line to appear only over the shebang, not over the entire file.
- When the shebang is missing and it is supposed to be there, we want the yellow squiggly line to appear on the first line, not over the entire file.

**Comment by aladdin-add** [comment]
yes, it's not a good UX to highlight the entire file. are you willing to submit a PR? :)

**Comment by Zamiell** [comment]
Sorry, I don't have time.
