### ISSUE TITLE
When will ignoreTypeImport in no-unpublished-import be published?

### ISSUE THREAD

**Issue by ashercoren** [eslint-community/eslint-plugin-n#92]
Hi;
We were very excited to find the ignoreTypeImport option in the no-unpublished-import, but we were really bummed to find out that it wasn't published to npm yet...
Do you have an idea when the latest code will be published?

**Comment by aladdin-add** [comment]
I was preparing a new major: https://github.com/eslint-community/eslint-plugin-n/issues/42

but, yes, I think it's fine to release this as a new minor. will do!

**Comment by aladdin-add** [comment]
released https://github.com/eslint-community/eslint-plugin-n/releases/tag/15.7.0.  🎉
